name: gallery_of_images
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-144.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Work With Api
  dio: ^5.6.0

  # Dependency injection
  get_it: ^7.7.0

  #BLoC
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Grid ui
  flutter_staggered_grid_view: ^0.7.0

  # Photo viewer
  photo_view: ^0.15.0

  # Network
  retrofit: ^4.2.0
  json_annotation: ^4.8.1

  # Navigation
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  # assets:
  #   - .env
